import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Template } from "@/components/layout-component/MainTemplate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Let it go App",
  description: "Generated by Let it go app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${inter.className}`}>
        <Template>{children}</Template>
      </body>
    </html>
  );
}
