import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Let it go App",
  description: "Generated by Let it go app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-slate-500 min-h-screen">
      <header>headi</header>
      {children}
      <footer>foote</footer>
    </div>
    
  );
}
